language: clojure
script: "lein pom && mvn test && lein javac"
notifications:
  slack: yeller:nHkgeCJkcwwjMF0DfOrmDccR
sudo: false
cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
