#!/bin/bash

lein with-profile test run -m org.junit.runner.JUnitCore com.yellerapp.test.endtoend.EndToEndTest com.yellerapp.test.unit.YellerReporterTest com.yellerapp.test.unit.ExceptionFormatterTest
